// import { Inter } from "next/font/google";
import Header from "@/components/layout/header"
// const inter = Inter({ subsets: ["latin"] });
import type { Metadata } from "next"

import "../../public/assets/styles/style.scss"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="root">
          <Header />
          <main>{children}</main>
          <footer>푸터 영역</footer>
        </div>
      </body>
    </html>
  )
}
